Feature/draft preview
alexkates/hashnode-next pull request #10
Opened 2024-02-18 10:18 UTC by lkrimphove

## What does this PR do?

Fixes #9

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How should this be tested?

- Create a draft in the Hashnode editor.
- Open the preview of this draft.
- The draft should be shown on your website.

### Things to remember

- [X] Filled out the "How to test" section in this PR
- [X] Read [Contributing Guide](./CONTRIBUTING.md)
- [X] Ran `pnpm build`
- [X] Ran `pnpm format`
- [X] Ran `pnpm lint`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`

2024-02-18 10:51 UTC, alexkates commented
@lkrimphove can you address the merge conflicts in `generated/graphql.ts`?

I've created a new issue to [exclude the generated files](https://github.com/alexkates/hashnode-next/issues/11) from git.

2024-02-19 11:19 UTC, alexkates requested changes
One minor name change and then it's good to go!

2024-02-19 11:19 UTC, alexkates commented on src/app/blog/preview/[id]/page.tsx
> +  const post = await getdraftDraft(params);
getBlogPostDraft*

2024-02-19 14:46 UTC, lkrimphove commented on src/app/blog/preview/[id]/page.tsx
> +  const post = await getdraftDraft(params);
Sorry for those mistakes. Fixed those and tested it again. Everything should work now. :)

2024-02-19 15:27 UTC, merged

2024-02-19 15:28 UTC, alexkates commented
Awesome! Thanks again @lkrimphove